# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 21:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('release_date', models.DateField()),
                ('rating', models.IntegerField()),
                ('image', models.ImageField(upload_to='albums')),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('track_location', models.FileField(upload_to='music')),
                ('album', models.ManyToManyField(to='siku.Album')),
            ],
        ),
        migrations.AddField(
            model_name='playlist',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siku.Track'),
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siku.Artist'),
        ),
    ]
